# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: [ '--pattern', '^(?!((release|enhancement|feature|bugfix|documentation|tests|local|chore)\/[a-zA-Z0-9\-_]+)$).*' ]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        additional_dependencies:
          - wemake-python-styleguide
          - flake8
        description: Python style guide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
